config/routes.rb
Rails.application.routes.draw do

  resources :chassis
  resources :chasses
  resources :matches, except: [:edit, :update, :destroy] do
    member do
      get 'processed_images/:slice_name', to: 'matches#processed_images'
    end
  end
  resources :screenshots

  root 'matches#index'
  get '/*foo', to: redirect('/')

end

app/models/chassis.rb
class Chassis < ActiveRecord::Base
  has_many :chassis_matches
end

app/models/chassis_match.rb
class ChassisMatch < ActiveRecord::Base
  belongs_to :chassis
  belongs_to :match
end

app/models/match.rb
class Match < ActiveRecord::Base

  require 'carrierwave/processing/mini_magick'

  has_many :screenshots
  accepts_nested_attributes_for :screenshots
  has_many :pilot_matches
  has_many :chassis_matches

  def map_name
  end

  def game_mode
  end

  def battle_duration
  end

  def screenshot
    return screenshots[0]
  end

end

app/models/pilot.rb
class Pilot < ActiveRecord::Base

  has_many :pilot_matches

end

app/models/pilot_matches.rb
class PilotMatch < ActiveRecord::Base

  belongs_to :pilot
  belongs_to :match

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base

  mount_uploader :image, ScreenshotImageUploader
  belongs_to :match

  def get_slice(height, width, x, y)
    size = "#{height}x#{width}"
    offset = "+#{x}+#{y}"
    mogrify_arg = "#{size}#{offset}"
    image.crop(mogrify_arg)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chassis_controller.rb
class ChassisController < ApplicationController
  before_action :set_chassi, only: [:show, :edit, :update, :destroy]

  # GET /chassis
  def index
    @chassis = Chassi.all
  end

  # GET /chassis/1
  def show
  end

  # GET /chassis/new
  def new
    @chassi = Chassi.new
  end

  # GET /chassis/1/edit
  def edit
  end

  # POST /chassis
  def create
    @chassi = Chassi.new(chassi_params)

    if @chassi.save
      redirect_to @chassi, notice: 'Chassi was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /chassis/1
  def update
    if @chassi.update(chassi_params)
      redirect_to @chassi, notice: 'Chassi was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /chassis/1
  def destroy
    @chassi.destroy
    redirect_to chassis_url, notice: 'Chassi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chassi
      @chassi = Chassi.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def chassi_params
      params[:chassi]
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :processed_images]
  after_action :delete_image_slices, only: [:show, :processed_images]

  def index
    @matches = Match.all
  end

  def show
  end

  def processed_images
    return unless request.post?
    return params[:slice_name]
  end

  def new
    @match = Match.new
    @match.screenshots.build
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to @match, notice: 'Match was successfully created.'
    else
      render :new
    end
  end

  private
    def set_match
      @match = Match.find(params[:id])
    end

    def delete_image_slices
      FileUtils.rm_rf("#{Rails.root}/test/fixtures/images/uploads", secure: true)
    end

    # Strong params
    def match_params
      params.require(:match).permit(screenshots_attributes: [:image])
    end

end

app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :set_screenshot, only: [:show, :edit, :update, :destroy]

  def index
    @screenshots = Screenshot.all
  end

  def show
  end

  def new
    @screenshot = Screenshot.new
  end

  def edit
  end

  def create
    @screenshot = Screenshot.new(screenshot_params)

    if @screenshot.save
      redirect_to @screenshot, notice: 'Screenshot was successfully created.'
    else
      render :new
    end
  end

  def update
    if @screenshot.update(screenshot_params)
      redirect_to @screenshot, notice: 'Screenshot was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @screenshot.destroy
    redirect_to screenshots_url, notice: 'Screenshot was successfully destroyed.'
  end

  private

    def set_screenshot
      @screenshot = Screenshot.find(params[:id])
    end

    # Strong params
    def screenshot_params
      params.require(:screenshot).permit(:image)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def front_page
  end

end

app/helpers/scoreboard_parser.rb
class ScoreboardParser
  require 'tesseract'

  def map_name
    img = slice_screenshot_image(magickimage, 135, 17, 460, 107)
    return ocr_engine(img)
  end

  def game_mode
    img = slice_screenshot_image(magickimage, 95, 17, 660, 107)
    return ocr_engine(img)
  end

  def battle_duration
    img = slice_screenshot_image(magickimage, 32, 17, 835, 107)
    return ocr_engine(img)
  end

  def player_a_team_b
    # take absolute offsets for red or blue
    # add relative offsets for player index in team
    # get slice
  end

  def team_scores
    blue_score = 0
    red_score = 0
    return { blue_score: blue_score, red_score: red_score }
  end

  private
    def ocr_engine
      return Tesseract::Engine.new do |e|
        e.language  = :eng
        e.blacklist = '|'
      end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carry Harder</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/matches/_form.html.haml
g= form_for @match, :html => {:multipart => true} do |f|
  - if @match.errors.any?
    #error_explanation
      %h2
        #{pluralize(@match.errors.count, "error")} prohibited this match from being saved:

      %ul
        - @match.errors.full_messages.each do |message|
          %li
            = message

  = f.fields_for :screenshots do |screenshots_form|
    = screenshots_form.file_field :image

  .actions
    = f.submit

app/views/matches/index.html.haml
%p#notice
  = notice

%h2
  Listing Matches
%h1
%br
= link_to 'New Match', new_match_path
%br
%br

- @matches.each do |match|
  = link_to match do
    = image_tag match.screenshot.image.thumbnail.url
  %br
  = link_to 'Show', match
  |
  = link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' }

%br
%br

app/views/matches/new.html.haml
%h1
  New Match

= render 'form'

= link_to 'Back', matches_path

app/views/matches/processed_images.html.haml
#notice
  = notice

= "#{@match.map_name} | #{@match.game_mode} | #{@match.battle_duration}"
%br
%br

= @match.screenshot.map_name_image.path
%br
= image_tag @match.screenshot.map_name_image.path
%br
%br
%br
= @match.screenshot.game_mode_image.path
%br
= image_tag @match.screenshot.game_mode_image.path
%br
%br
%br
= @match.screenshot.battle_duration_image.path
%br
= image_tag @match.screenshot.battle_duration_image.path
%br

= image_tag @match.screenshot.image.map_name_slice.url
= image_tag @match.screenshot.image.game_mode_slice.url
= image_tag @match.screenshot.image.battle_duration_slice.url
%br
= image_tag @match.screenshot.image.url

%br
= link_to 'New', new_match_path
|
= link_to 'Back', matches_path

app/views/matches/show.html.haml
#notice
  = notice
  
= "#{@match.map_name} | #{@match.game_mode} | #{@match.battle_duration}"
%br
%br

= image_tag @match.screenshot.image.map_name_slice.url
= image_tag @match.screenshot.image.game_mode_slice.url
= image_tag @match.screenshot.image.battle_duration_slice.url
%br
= image_tag @match.screenshot.image.url

%br
= link_to 'New', new_match_path
|
= link_to 'Back', matches_path

app/views/screenshots/_form.html.haml
= form_for @screenshot, :html => {:multipart => true} do |f|
  - if @screenshot.errors.any?
    #error_explanation
      %h2
        #{pluralize(@screenshot.errors.count, "error")} prohibited this screenshot from being saved:

      %ul
        - @screenshot.errors.full_messages.each do |message|
          %li
            = message

  = f.file_field :image

  .actions
    = f.submit

app/views/screenshots/index.html.haml
%p#notice
  = flash[:notice]

%h1
  Listing Screenshots

- @screenshots.each do |screenshot|


  = image_tag screenshot.image_url.to_s
  %br
  = link_to 'Show', screenshot
  |
  = link_to 'Edit', edit_screenshot_path(screenshot)
  |
  = link_to 'Destroy', screenshot, method: :delete, data: { confirm: 'Are you sure?' }
  %br

%br
%br

= link_to 'New Screenshot', new_screenshot_path

app/views/screenshots/new.html.haml
%h1
  New Screenshot

= render 'form'

= link_to 'Back', screenshots_path

app/views/screenshots/show.html.haml
#notice
  = notice

= image_tag @screenshot.image_url.to_s

%br
= link_to 'New', new_screenshot_path
|
= link_to 'Edit', edit_screenshot_path(@screenshot)
|
= link_to 'Back', screenshots_path